export class Event {

  static RADIAL_REQUESTED = 'RADIAL_REQUESTED'
  static DUPLICATE_RADIAL_REQUESTED = 'DUPLICATE_RADIAL_REQUESTED'
  static RADIAL_ADDED = 'RADIAL_ADDED'
  static RADIAL_UPDATED = 'RADIAL_UPDATED'
  static RADIAL_REMOVED = 'RADIAL_REMOVED'
  static SELECTION_CHANGE: ArgFreeEventType = 'selectionchange'
  static PLUGIN_CLOSE: ArgFreeEventType = 'close'

  static RADIAL_DELETED_ON_CANVAS = 'RADIAL_DELETED_ON_CANVAS'
}